#!/bin/sh
username="ludovic"

echo "Status $username on Milou"
echo "Total Jobs:"
jobinfo -u $username | grep $username | wc -l
echo "Running Jobs:"
jobinfo -u $username | grep -E "\sm[0-9]." | wc -l
echo "Waiting Jobs:"
jobinfo -u $username |  grep "Waiting jobs" -A 10000 | grep $username | wc -l

#finding where we wait from
echo "First Job in queue:"
jobinfo -u $username |  grep "Waiting jobs" -A 2 | grep -v POS | grep -v Waiting
echo "Next job to run out of time:"
jobinfo -u $username |  grep "Running jobs" -A 2 | grep -v TIME | grep -v Running

